# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: scfhao 的个人博客
email: scfhao@gmail.com
mailto: "邮件联系"
description: > # this means to ignore newlines until "baseurl:"
  scfhao 博客
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://scfhao.coding.me/blog" # the base hostname & protocol for your site
# twitter_username: scfhao
github_username: scfhao
weibo_username: scfhao
exclude: ["Rakefile"]

# Coding Comments Settings
coding_comments:
	user: 'scfhao'
	project: 'blog'
	oauth:
		client_id: 'f8aa44aed6291c6cdcd9696391fe815e'
		client_secret: 'f431664e0eedc0b7b2872fc7fc0942c07a7e6dd9'

# Build settings
markdown: kramdown