# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: scfhao 的个人博客
email: scfhao@126.com
mailto: "邮件联系"
description: > # this means to ignore newlines until "baseurl:"
  scfhao 博客
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.scfhao.cn" # the base hostname & protocol for your site
# twitter_username: scfhao
github_username: scfhao
weibo_username: scfhao
exclude: ["Rakefile"]
# Build settings
markdown: kramdown
# Leancloud
valine:
  AppID: yqQA8xRYOn9OWYPxcAci81Gk-gzGzoHsz
  AppKey: aFDUX2tUnEJPgTlsBpdxysDT
